name: Test HyCAN
on:
  push:
jobs:
  test-project:
    name: Run CTest
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          # Enable multiverse repository
          sudo add-apt-repository multiverse
          sudo apt-get update

          # Install GCC-14
          sudo apt-get install -y gcc-14 g++-14 linux-modules-extra-$(uname -r)

          # Configure update-alternatives for GCC-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 140 \
                                   --slave /usr/bin/g++ g++ /usr/bin/g++-14 \
                                   --slave /usr/bin/gcov gcov /usr/bin/gcov-14

          # Verify GCC version
          gcc --version
          g++ --version

      - name: Load CAN Module
        run: |
          sudo modprobe vcan
          sudo modprobe can

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          generator: Ninja
          cxx-compiler: g++
          c-compiler: gcc
          options: |
            BUILD_HYCAN_TEST=ON
            CMAKE_BUILD_TYPE=Release

      - name: Test Project
        run: |
          cd build
          sudo ctest --output-on-failure