name: Test HyCAN
on:
  push:
jobs:
  test-project:
    name: Run CTest
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19
          sudo apt install -y clang-tools-19 libc++-dev libc++abi-dev linux-modules-extra-$(uname -r)

      - name: Load CAN Module
        run: |
          sudo modprobe vcan
          sudo modprobe can

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Install Conan
        uses: conan-io/setup-conan@v1

      - name: Install Conan dependencies
        run: conan install . --build=missing -s compiler=clang -s compiler.cppstd=gnu23 -s compiler.libcxx=libstdc++11 -s compiler.version=19 -s:b compiler=clang -s:b compiler.cppstd=gnu23 -s:b compiler.libcxx=libstdc++11 -s:b compiler.version=19

      - name: Build Project
        run: |
          cmake --preset conan-release -G Ninja -DBUILD_HYCAN_TEST=ON
          cmake --build --preset conan-release

      - name: Test Project
        run: |
          cd build/Release
          sudo ctest --output-on-failure