name: Test HyCAN
on:
  push:
jobs:
  test-project:
    name: Run CTest
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt install -y linux-modules-extra-$(uname -r)

      - name: Load CAN Module
        run: |
          sudo modprobe vcan
          sudo modprobe can

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Install Conan
        uses: conan-io/setup-conan@v1

      - name: Install Conan dependencies
        run: |
          conan profile detect
          DEFAULT_PROFILE_PATH=$(conan profile path default)
          if [ -f "$DEFAULT_PROFILE_PATH" ]; then
            sed -i "s|^compiler.cppstd=.*|compiler.cppstd=gnu23|" "$DEFAULT_PROFILE_PATH"
            echo "Updated compiler.cppstd to gnu23 in $DEFAULT_PROFILE_PATH"
            echo "You can verify with: conan profile show default | grep cppstd"
          else
            echo "Error: Default profile path not found at $DEFAULT_PROFILE_PATH"
          fi
          conan install . --build=missing
      - name: Build Project
        run: |
          cmake --preset conan-release -G Ninja -DBUILD_HYCAN_TEST=ON
          cmake --build --preset conan-release

      - name: Test Project
        run: |
          cd build/Release
          sudo ctest --output-on-failure