name: Test HyCAN
on:
  push:
jobs:
  test-project:
    name: Run CTest
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y linux-modules-extra-$(uname -r)

      - name: Load CAN Module
        run: |
          sudo modprobe vcan
          sudo modprobe can

      - name: Setup cmake
        uses: lukka/get-cmake@latest

      - name: Build Project
        run: |
          cmake -S . -B build -G Ninja -DBUILD_HYCAN_TEST=ON -DTEST_HYCAN_LATENCY=ON
          cmake --build build

      - name: Test Project
        run: |
          cd build
          sudo ctest --output-on-failure