name: Test HyCAN
on:
  push:
jobs:
  test-project:
    name: Run CTest
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          # Enable multiverse repository
          sudo add-apt-repository multiverse
          sudo apt-get update

          # Install GCC-14
          sudo apt-get install -y gcc-14 g++-14 linux-modules-extra-$(uname -r)

          # Configure update-alternatives for GCC-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 140 \
                                   --slave /usr/bin/g++ g++ /usr/bin/g++-14 \
                                   --slave /usr/bin/gcov gcov /usr/bin/gcov-14

          # Verify GCC version
          gcc --version
          g++ --version

      - name: Load CAN Module
        run: |
          sudo modprobe vcan
          sudo modprobe can

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Install Conan
        uses: conan-io/setup-conan@v1

      - name: Install Conan dependencies
        run: conan install . --build=missing

      - name: Build Project
        run: |
          cd build
          cmake --preset conan-release -G Ninja
          cmake --build --preset conan-release -G Ninja -DBUILD_HYCAN_TEST=ON

      - name: Test Project
        run: |
          cd build
          sudo ctest --output-on-failure