name: Test HyCAN
on:
  push:
jobs:
  test-project:
    name: Run CTest
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 20
          sudo apt install libc++-dev libc++abi-dev

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          generator: Ninja
          cxx-compiler: clang++
          c-compiler: clang
          options: |
            BUILD_HYCAN_TEST=ON
            CMAKE_CXX_FLAGS="-stdlib=libc++"
            CMAKE_EXE_LINKER_FLAGS="-stdlib=libc++"
            CMAKE_SHARED_LINKER_FLAGS="-stdlib=libc++"
            CMAKE_BUILD_TYPE=Release

      - name: Test Project
        run: |
          cd build
          sudo ctest --output-on-failure